language: node_js
node_js:
  - "lts/*"
  - "8"
env:
  - test

services:
  - mysql

notifications:
  slack: ynov-estei:nTlYzaNbdjJua7nvXoPR3k3q

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - ./node_modules/.bin/sequelize db:create
  - ./node_modules/.bin/sequelize db:migrate
  - ./node_modules/.bin/sequelize db:seed:all
  - npm run test
