language: node_js
node_js:
  - "lts/*"
  - "8"
env:
  - test

services:
  - mysql

notifications:
  email:
    - julien.boyer@ynov.com
    - francois.poisblaud@gmail.com
    - chabertcamille@live.com
    - julien.mustiere@ntymail.com

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - ./node_modules/.bin/sequelize db:create
  - ./node_modules/.bin/sequelize db:migrate
  - ./node_modules/.bin/sequelize db:seed:all
  - npm run test
